import '@servicenow/sdk/global'
import { RestApi } from '@servicenow/sdk/core'
import { createSession, joinSession, joinSessionAlternative } from '../../server/rest-handlers/session-handlers.js'
import { startVoting, submitVote, revealVotes, finalizeSession } from '../../server/rest-handlers/voting-handlers.js'

export const cabPokerApi = RestApi({
    $id: Now.ID['cab-poker-api'],
    name: 'CAB Poker API',
    service_id: 'cab_poker',
    short_description: 'REST API for CAB Poker voting sessions',
    active: true,
    enforce_acl: [],
    routes: [
        {
            $id: Now.ID['create-session'],
            name: 'Create Session',
            path: '/session',
            method: 'POST',
            script: createSession,
            short_description: 'Create a new CAB voting session',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['join-session'],
            name: 'Join Session',
            path: '/session/join',
            method: 'POST',
            script: joinSession,
            short_description: 'Join an existing CAB voting session using session code',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['join-session-alt'],
            name: 'Join Session Alternative',
            path: '/join/{session_code}',
            method: 'GET',
            script: joinSessionAlternative,
            short_description: 'Alternative method to join session using path parameter',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['start-voting'],
            name: 'Start Voting',
            path: '/session/{session_id}/start-voting',
            method: 'POST',
            script: startVoting,
            short_description: 'Start voting for a change request (chair only)',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['submit-vote'],
            name: 'Submit Vote',
            path: '/session/{session_id}/vote',
            method: 'POST',
            script: submitVote,
            short_description: 'Submit votes for risk, impact, and recommendation',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['reveal-votes'],
            name: 'Reveal Votes',
            path: '/session/{session_id}/reveal',
            method: 'POST',
            script: revealVotes,
            short_description: 'Reveal all votes for the session (chair only)',
            authentication: true,
            authorization: true,
        },
        {
            $id: Now.ID['finalize-session'],
            name: 'Finalize Session',
            path: '/session/{session_id}/finalize',
            method: 'POST',
            script: finalizeSession,
            short_description: 'Chair sets final risk/impact/recommendation and completes the session',
            authentication: true,
            authorization: true,
        },
    ],
})